myName = input("what's your name?: ")
myAge = input("How old are you? :")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)
#This is new section
myLunch = input("What are you having for lunch? ")
print("Hmm, it like you really should just order")
print(myLaunch)
print("as soon as possible!")